# Generates some boilerplate JSON for examples (autogenerated ID, timestamp, etc)

require 'json'
require 'date'
require 'securerandom'

type = (ARGV[0] || STDIN.gets).chomp.strip

obj = {
  type: type,
  id: "example.com:#{SecureRandom.uuid}",
  created_at: DateTime.now.rfc3339(6),
  producer_ref: 'example.com:example'
}

puts JSON.pretty_generate(obj)
